production: &defaults
  adapter: redis
  url: redis://redis-19756.c74.us-east-1-4.ec2.cloud.redislabs.com:19756
  password: abcd
  timeout: 1
  

development:
  <<: *defaults
  url: redis://localhost:6379/2

test:
  <<: *defaults
  url: redis://localhost:6379/3
