defaults: &defaults
  host: 127.0.0.1:11211
  namespace: rb-1
  compress: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  host: memcached-14251.c12.us-east-1-4.ec2.cloud.redislabs.com:14251
  namespace: rb-1
  compress: true